### ISSUE TITLE
Add support for pod/deployment labels and annotations

### ISSUE THREAD

**Issue by hjoshi123** [projectsveltos/helm-charts#115]
Currently, the `projectsveltos` charts doesn't support for custom labels for either the deployment or the pod spec. I would like to change this behavior and add the feature of providing user inputs similar to either a global object which adds labels to all resources or podLabels and annotations which adds it to the pod only.

A basic amend would be here:

```yaml
labels:
    control-plane: addon-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
```

I am interested in putting up a patch for the same.
