### ISSUE TITLE
Sveltos deploying Sveltos

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/helm-charts#66]
When Sveltos is used to deploy Sveltos on another managed cluster, following ClusterProfile 

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-cert-manager
spec:
  clusterSelector:
    matchLabels:
      env: mgmt
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://charts.jetstack.io
    repositoryName:   jetstack
    chartName:        jetstack/cert-manager
    chartVersion:     v1.16.0
    releaseName:      cert-manager
    releaseNamespace: cert-manager
    helmChartAction:  Install
    values: |
      crds:
        enabled: true
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-projectsveltos
spec:
  clusterSelector:
    matchLabels:
      env: mgmt
  dependsOn:
  - deploy-cert-manager
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://projectsveltos.github.io/helm-charts
    repositoryName:   projectsveltos
    chartName:        projectsveltos/projectsveltos
    chartVersion:     v0.38.4
    releaseName:      projectsveltos
    releaseNamespace: projectsveltos
    helmChartAction:  Install
```

fails with

```
failureMessage: "post-upgrade hooks failed: warning: Hook post-upgrade projectsveltos/templates/default-classifier.yaml
        failed: 1 error occurred:\n\t* classifiers.lib.projectsveltos.io \"default-classifier\"
```
