### ISSUE TITLE
Enhance get_digest.sh script

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/helm-charts#87]
Currently [get_digest.sh](https://github.com/projectsveltos/helm-charts/blob/main/scripts/get_digest.sh) only gets digests for Sveltos images given a tag. 

A nice enhancement would be for it to automatically update [values.yaml](https://github.com/projectsveltos/helm-charts/blob/main/charts/projectsveltos/values.yaml)

For every Sveltos components there is a section like this

```
    image:
      repository: docker.io/projectsveltos/access-manager
      tag: v0.46.1
      digest: sha256:c7794284849869f58c8bbb4df0effa89b7a7ede4944ee13b59dcd1693f19b168
```

it would be nice to extend get_digest.sh to get digest, and then update this section. For instance lets say we run

./get_digest.sh  v0.47.0

starting from 

```
    image:
      repository: docker.io/projectsveltos/access-manager
      tag: v0.46.1
      digest: sha256:c7794284849869f58c8bbb4df0effa89b7a7ede4944ee13b59dcd1693f19b168
```

after getting the digest for access-manager v0.47.0 this could be 

```
    image:
      repository: docker.io/projectsveltos/access-manager
      tag: v0.47.0
      digest: sha256:xxxxxxxxxxxxxxxx
```
